import { Injectable, Logger, Inject, forwardRef } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { getAIClient } from '@aidevops/ai-client';
import { IncidentAlertEntity, RootCauseAnalysisEntity, RollbackEventEntity, IncidentTimelineEntity } from '../../entities';
import { DeploymentsService } from '../deployments/deployments.service';
import { NotificationsService } from '../notifications/notifications.service';
import { EventsGateway } from '../gateway/gateway.module';

@Injectable()
export class IncidentsService {
  private readonly logger = new Logger(IncidentsService.name);

  constructor(
    @InjectRepository(IncidentAlertEntity) private incidentRepo: Repository<IncidentAlertEntity>,
    @InjectRepository(RootCauseAnalysisEntity) private rcaRepo: Repository<RootCauseAnalysisEntity>,
    @InjectRepository(RollbackEventEntity) private rollbackRepo: Repository<RollbackEventEntity>,
    @InjectRepository(IncidentTimelineEntity) private timelineRepo: Repository<IncidentTimelineEntity>,
    private readonly deploymentsService: DeploymentsService,
    private readonly notificationsService: NotificationsService,
    @Inject(forwardRef(() => EventsGateway)) private readonly eventsGateway: EventsGateway,
  ) {}

  // ─── Timeline Helper ─────────────────────────────────────────────────────────

  async addTimelineEvent(
    incidentId: string,
    type: string,
    title: string,
    description: string,
  ): Promise<IncidentTimelineEntity> {
    const event = this.timelineRepo.create({
      incidentId,
      type,
      title,
      description,
    });
    const saved = await this.timelineRepo.save(event);
    this.logger.log(`[Timeline] Incident ${incidentId} transition: "${title}" (${type})`);

    // Emit live WebSocket update
    try {
      let orgId = 'default-org';
      const res = await this.incidentRepo.createQueryBuilder('i')
        .innerJoin('projects', 'p', 'i.projectId = p.id')
        .where('i.id = :incidentId', { incidentId })
        .select('p.organizationId', 'orgId')
        .getRawOne();
      if (res && res.orgId) {
        orgId = res.orgId;
      }

      this.eventsGateway.emitGlobalEvent(orgId, `incident:${incidentId}:timeline`, saved);
      this.eventsGateway.emitGlobalEvent(orgId, 'incident:timeline:update', { incidentId, event: saved });
    } catch (err) {
      this.logger.warn(`Failed to emit timeline live update: ${err.message}`);
    }

    return saved;
  }

  async getTimeline(incidentId: string, organizationId: string): Promise<IncidentTimelineEntity[]> {
    return this.timelineRepo.createQueryBuilder('t')
      .innerJoin('incident_alerts', 'i', 't.incidentId = i.id')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('t.incidentId = :incidentId', { incidentId })
      .andWhere('p.organizationId = :organizationId', { organizationId })
      .orderBy('t.timestamp', 'ASC')
      .getMany();
  }

  // ─── Webhook Handling & Correlation ──────────────────────────────────────────

  async handleIncidentWebhook(payload: any): Promise<any> {
    this.logger.log(`Received incident webhook from ${payload.source || 'unknown'}`);
    
    // 1. T5.2 Automatic Event Correlation
    let deploymentId = payload.deploymentId;
    if (!deploymentId && payload.projectId) {
      const correlatedDeployment = await this.deploymentsService.findLatestForProject(payload.projectId);
      if (correlatedDeployment) {
        deploymentId = correlatedDeployment.id;
        this.logger.log(`Correlated incident alert to latest active deployment: ${deploymentId}`);
      }
    }

    // 2. Save Incident
    const incident = this.incidentRepo.create({
      projectId: payload.projectId || 'unknown',
      deploymentId: deploymentId || null,
      environment: payload.environment || 'production',
      source: payload.source || 'custom',
      severity: payload.severity || 'high',
      title: payload.title || 'Unknown Incident',
      description: payload.description || '',
      metric: payload.metric,
      value: payload.value,
      threshold: payload.threshold,
      status: 'open',
    });
    const savedIncident = await this.incidentRepo.save(incident);

    // 3. T5.4 Incident Lifecycle Detected Checkpoint
    await this.addTimelineEvent(
      savedIncident.id,
      'detected',
      'Anomaly Detected',
      `Alert generated by ${payload.source || 'Monitoring Agent'}. Description: ${payload.description || 'No description provided'}`
    );

    // Emit live WebSocket event
    let projectOrgId = 'default-org';
    try {
      if (savedIncident.projectId && savedIncident.projectId !== 'unknown') {
        const res = await this.incidentRepo.createQueryBuilder('i')
          .innerJoin('projects', 'p', 'i.projectId = p.id')
          .select('p.organizationId', 'orgId')
          .where('i.id = :id', { id: savedIncident.id })
          .getRawOne();
        if (res && res.orgId) {
          projectOrgId = res.orgId;
        }
      }
      this.eventsGateway.emitGlobalEvent(projectOrgId, 'incident:created', savedIncident);
    } catch (err) {
      this.logger.warn(`Failed to emit incident:created: ${err.message}`);
    }

    // 4. AI RCA Generation & Stepping
    let savedRca = null;
    try {
      const aiClient = getAIClient();
      this.logger.log(`Generating RCA for incident ${savedIncident.id}...`);
      const rcaResult = await aiClient.generateRCA(savedIncident);
      
      // Save RCA
      const rca = this.rcaRepo.create({
        incidentId: savedIncident.id,
        summary: rcaResult.summary,
        hypothesis: rcaResult.hypothesis,
        rootCause: rcaResult.rootCause,
        affectedComponents: rcaResult.affectedComponents,
        recommendedActions: rcaResult.recommendedActions,
        confidenceScore: rcaResult.confidenceScore,
      });
      savedRca = await this.rcaRepo.save(rca);

      // T5.4 RCA Timeline Checkpoint
      await this.addTimelineEvent(
        savedIncident.id,
        'rca_generated',
        'AI Risk Correlated',
        `AI generated Root Cause Analysis with ${rcaResult.confidenceScore}% confidence. Root cause: "${rcaResult.rootCause}"`
      );
    } catch (err) {
      this.logger.error(`AI RCA generation failed: ${err.message}`);
    }

    // 5. Trigger Auto-Rollback if critical and deployment exists
    let rollbackEvent = null;
    if (savedIncident.severity === 'critical' && savedIncident.deploymentId) {
      this.logger.warn(`Critical incident detected. Initiating auto-rollback for deployment ${savedIncident.deploymentId}`);
      
      // T5.4 Rollback Started Timeline Checkpoint
      await this.addTimelineEvent(
        savedIncident.id,
        'rollback_started',
        'Auto-Rollback Triggered',
        `Initiating automated container rollback to recover gateway timeout and active user sessions.`
      );

      try {
        const rollbackResult = await this.deploymentsService.rollback(
          savedIncident.deploymentId,
          'Auto-rollback triggered by critical incident',
          projectOrgId
        );
        
        if (rollbackResult) {
          rollbackEvent = this.rollbackRepo.create({
            incidentId: savedIncident.id,
            deploymentId: savedIncident.deploymentId,
            previousDeploymentId: rollbackResult.id,
            status: 'success',
            reason: 'Auto-rollback triggered by critical incident',
            triggeredBy: 'auto',
            completedAt: new Date(),
          });
          await this.rollbackRepo.save(rollbackEvent);

          // T5.4 Rollback Completed Timeline Checkpoint
          await this.addTimelineEvent(
            savedIncident.id,
            'rollback_completed',
            'Auto-Rollback Completed',
            `Successfully rolled back active container images to stable tags (previous deployment: ${rollbackResult.id}).`
          );
        }
      } catch (err) {
        this.logger.error(`Failed to execute auto-rollback: ${err.message}`);
        await this.addTimelineEvent(
          savedIncident.id,
          'rollback_failed',
          'Auto-Rollback Failed',
          `Automated rollback script encountered an error: ${err.message}`
        );
      }
    }

    // 6. Notify Team
    await this.notificationsService.sendIncidentNotification(savedIncident, savedRca, rollbackEvent);

    return {
      incident: savedIncident,
      rca: savedRca,
      rollback: rollbackEvent,
    };
  }

  async getIncidents(organizationId: string, projectId?: string): Promise<any[]> {
    const qb = this.incidentRepo.createQueryBuilder('i')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .leftJoin('deployments', 'd', 'i.deploymentId = d.id')
      .leftJoin('pipeline_runs', 'pr', 'd.pipelineRunId = pr.id')
      .leftJoin('approval_requests', 'ar', 'ar.pipelineRunId = pr.id')
      .leftJoin('ai_review_results', 'ai', 'ai.pipelineRunId = pr.id')
      .where('p.organizationId = :organizationId', { organizationId })
      .select([
        'i.id AS id',
        'i.projectId AS "projectId"',
        'i.deploymentId AS "deploymentId"',
        'i.environment AS environment',
        'i.source AS source',
        'i.severity AS severity',
        'i.title AS title',
        'i.description AS description',
        'i.metric AS metric',
        'i.value AS value',
        'i.threshold AS threshold',
        'i.status AS status',
        'i.resolvedAt AS "resolvedAt"',
        'i.timestamp AS timestamp',
        'p.name AS "projectName"',
        'd.imageTag AS "deploymentImageTag"',
        'pr.commitSha AS "commitSha"',
        'pr.branch AS branch',
        'ar.reviewedBy AS "approvedBy"',
        'ai.riskScore AS "riskScore"',
      ]);

    if (projectId) {
      qb.andWhere('i.projectId = :projectId', { projectId });
    }

    const raw = await qb.orderBy('i.timestamp', 'DESC').getRawMany();
    return raw.map(item => ({
      ...item,
      value: item.value ? parseFloat(item.value) : undefined,
      threshold: item.threshold ? parseFloat(item.threshold) : undefined,
      riskScore: typeof item.riskScore === 'object' && item.riskScore !== null ? (item.riskScore.overall ?? item.riskScore) : item.riskScore,
    }));
  }

  async getRCA(incidentId: string, organizationId: string): Promise<RootCauseAnalysisEntity | null> {
    return this.rcaRepo.createQueryBuilder('rca')
      .innerJoin('incident_alerts', 'i', 'rca.incidentId = i.id')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('rca.incidentId = :incidentId', { incidentId })
      .andWhere('p.organizationId = :organizationId', { organizationId })
      .getOne();
  }

  async updateStatus(incidentId: string, status: string, organizationId: string): Promise<IncidentAlertEntity | null> {
    const incident = await this.incidentRepo.createQueryBuilder('i')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('i.id = :incidentId', { incidentId })
      .andWhere('p.organizationId = :organizationId', { organizationId })
      .getOne();
    if (!incident) return null;
    
    const oldStatus = incident.status;
    incident.status = status;
    if (status === 'resolved') {
      incident.resolvedAt = new Date();
    }
    const finalSaved = await this.incidentRepo.save(incident);

    // T5.4 Timeline lifecycle status checkpoint
    if (status === 'investigating') {
      await this.addTimelineEvent(
        incidentId,
        'investigating',
        'SRE Investigation Started',
        `Incident marked as investigating. SRE team is analyzing live telemetry.`
      );
    } else if (status === 'resolved') {
      await this.addTimelineEvent(
        incidentId,
        'resolved',
        'Incident Resolved',
        `Telemetry metrics returned to normal thresholds. Incident marked as resolved.`
      );
    }

    // Emit live WebSocket event
    try {
      this.eventsGateway.emitGlobalEvent(organizationId, 'incident:resolved', finalSaved);
    } catch (err) {
      this.logger.warn(`Failed to emit incident:resolved: ${err.message}`);
    }

    return finalSaved;
  }

  async getStats(organizationId: string) {
    const incidents = await this.incidentRepo.createQueryBuilder('i')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('p.organizationId = :organizationId', { organizationId })
      .orderBy('i.timestamp', 'DESC')
      .take(200)
      .getMany();
    const total = incidents.length;
    const active = incidents.filter(i => i.status !== 'resolved').length;
    const resolved = incidents.filter(i => i.status === 'resolved').length;

    // Compute avg MTTR from resolved incidents
    const resolvedIncidents = incidents.filter(i => i.status === 'resolved' && i.resolvedAt);
    let avgMttrMs = 0;
    if (resolvedIncidents.length > 0) {
      const totalMs = resolvedIncidents.reduce((sum, i) => {
        const ms = new Date(i.resolvedAt!).getTime() - new Date(i.timestamp).getTime();
        return sum + ms;
      }, 0);
      avgMttrMs = totalMs / resolvedIncidents.length;
    }
    const avgMttrMinutes = Math.round(avgMttrMs / 60000);
    const avgMttr = avgMttrMinutes > 0 ? `${avgMttrMinutes}m` : 'N/A';

    const rcaCount = await this.rcaRepo.createQueryBuilder('rca')
      .innerJoin('incident_alerts', 'i', 'rca.incidentId = i.id')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('p.organizationId = :organizationId', { organizationId })
      .getCount();

    const autoRollbacks = await this.rollbackRepo.createQueryBuilder('r')
      .innerJoin('incident_alerts', 'i', 'r.incidentId = i.id')
      .innerJoin('projects', 'p', 'i.projectId = p.id')
      .where('p.organizationId = :organizationId', { organizationId })
      .andWhere('r.triggeredBy = :auto', { auto: 'auto' })
      .getCount();

    return { total, active, resolved, avgMttr, rcaGenerated: rcaCount, autoRollbacks };
  }
}
