import { Injectable, Logger, Inject, forwardRef } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { getAIClient } from '@aidevops/ai-client';
import { IncidentAlertEntity, RootCauseAnalysisEntity, RollbackEventEntity, IncidentTimelineEntity } from '../../entities';
import { DeploymentsService } from '../deployments/deployments.service';
import { NotificationsService } from '../notifications/notifications.service';
import { EventsGateway } from '../gateway/gateway.module';

@Injectable()
export class IncidentsService {
  private readonly logger = new Logger(IncidentsService.name);

  constructor(
    @InjectRepository(IncidentAlertEntity) private incidentRepo: Repository<IncidentAlertEntity>,
    @InjectRepository(RootCauseAnalysisEntity) private rcaRepo: Repository<RootCauseAnalysisEntity>,
    @InjectRepository(RollbackEventEntity) private rollbackRepo: Repository<RollbackEventEntity>,
    @InjectRepository(IncidentTimelineEntity) private timelineRepo: Repository<IncidentTimelineEntity>,
    private readonly deploymentsService: DeploymentsService,
    private readonly notificationsService: NotificationsService,
    @Inject(forwardRef(() => EventsGateway)) private readonly eventsGateway: EventsGateway,
  ) {}

  // ─── Timeline Helper ─────────────────────────────────────────────────────────

  async addTimelineEvent(
    incidentId: string,
    type: string,
    title: string,
    description: string,
  ): Promise<IncidentTimelineEntity> {
    const event = this.timelineRepo.create({
      incidentId,
      type,
      title,
      description,
    });
    const saved = await this.timelineRepo.save(event);
    this.logger.log(`[Timeline] Incident ${incidentId} transition: "${title}" (${type})`);

    // Emit live WebSocket update
    try {
      this.eventsGateway.emitGlobalEvent(`incident:${incidentId}:timeline`, saved);
      this.eventsGateway.emitGlobalEvent('incident:timeline:update', { incidentId, event: saved });
    } catch (err) {
      this.logger.warn(`Failed to emit timeline live update: ${err.message}`);
    }

    return saved;
  }

  async getTimeline(incidentId: string): Promise<IncidentTimelineEntity[]> {
    return this.timelineRepo.find({
      where: { incidentId },
      order: { timestamp: 'ASC' },
    });
  }

  // ─── Webhook Handling & Correlation ──────────────────────────────────────────

  async handleIncidentWebhook(payload: any): Promise<any> {
    this.logger.log(`Received incident webhook from ${payload.source || 'unknown'}`);
    
    // 1. T5.2 Automatic Event Correlation
    let deploymentId = payload.deploymentId;
    if (!deploymentId && payload.projectId) {
      const correlatedDeployment = await this.deploymentsService.findLatestForProject(payload.projectId);
      if (correlatedDeployment) {
        deploymentId = correlatedDeployment.id;
        this.logger.log(`Correlated incident alert to latest active deployment: ${deploymentId}`);
      }
    }

    // 2. Save Incident
    const incident = this.incidentRepo.create({
      projectId: payload.projectId || 'unknown',
      deploymentId: deploymentId || null,
      environment: payload.environment || 'production',
      source: payload.source || 'custom',
      severity: payload.severity || 'high',
      title: payload.title || 'Unknown Incident',
      description: payload.description || '',
      metric: payload.metric,
      value: payload.value,
      threshold: payload.threshold,
      status: 'open',
    });
    const savedIncident = await this.incidentRepo.save(incident);

    // 3. T5.4 Incident Lifecycle Detected Checkpoint
    await this.addTimelineEvent(
      savedIncident.id,
      'detected',
      'Anomaly Detected',
      `Alert generated by ${payload.source || 'Monitoring Agent'}. Description: ${payload.description || 'No description provided'}`
    );

    // Emit live WebSocket event
    try {
      this.eventsGateway.emitGlobalEvent('incident:created', savedIncident);
    } catch (err) {
      this.logger.warn(`Failed to emit incident:created: ${err.message}`);
    }

    // 4. AI RCA Generation & Stepping
    let savedRca = null;
    try {
      const aiClient = getAIClient();
      this.logger.log(`Generating RCA for incident ${savedIncident.id}...`);
      const rcaResult = await aiClient.generateRCA(savedIncident);
      
      // Save RCA
      const rca = this.rcaRepo.create({
        incidentId: savedIncident.id,
        summary: rcaResult.summary,
        hypothesis: rcaResult.hypothesis,
        rootCause: rcaResult.rootCause,
        affectedComponents: rcaResult.affectedComponents,
        recommendedActions: rcaResult.recommendedActions,
        confidenceScore: rcaResult.confidenceScore,
      });
      savedRca = await this.rcaRepo.save(rca);

      // T5.4 RCA Timeline Checkpoint
      await this.addTimelineEvent(
        savedIncident.id,
        'rca_generated',
        'AI Risk Correlated',
        `AI generated Root Cause Analysis with ${rcaResult.confidenceScore}% confidence. Root cause: "${rcaResult.rootCause}"`
      );
    } catch (err) {
      this.logger.error(`AI RCA generation failed: ${err.message}`);
    }

    // 5. Trigger Auto-Rollback if critical and deployment exists
    let rollbackEvent = null;
    if (savedIncident.severity === 'critical' && savedIncident.deploymentId) {
      this.logger.warn(`Critical incident detected. Initiating auto-rollback for deployment ${savedIncident.deploymentId}`);
      
      // T5.4 Rollback Started Timeline Checkpoint
      await this.addTimelineEvent(
        savedIncident.id,
        'rollback_started',
        'Auto-Rollback Triggered',
        `Initiating automated container rollback to recover gateway timeout and active user sessions.`
      );

      try {
        const rollbackResult = await this.deploymentsService.rollback(
          savedIncident.deploymentId,
          'Auto-rollback triggered by critical incident'
        );
        
        if (rollbackResult) {
          rollbackEvent = this.rollbackRepo.create({
            incidentId: savedIncident.id,
            deploymentId: savedIncident.deploymentId,
            previousDeploymentId: rollbackResult.id,
            status: 'success',
            reason: 'Auto-rollback triggered by critical incident',
            triggeredBy: 'auto',
            completedAt: new Date(),
          });
          await this.rollbackRepo.save(rollbackEvent);

          // T5.4 Rollback Completed Timeline Checkpoint
          await this.addTimelineEvent(
            savedIncident.id,
            'rollback_completed',
            'Auto-Rollback Completed',
            `Successfully rolled back active container images to stable tags (previous deployment: ${rollbackResult.id}).`
          );
        }
      } catch (err) {
        this.logger.error(`Failed to execute auto-rollback: ${err.message}`);
        await this.addTimelineEvent(
          savedIncident.id,
          'rollback_failed',
          'Auto-Rollback Failed',
          `Automated rollback script encountered an error: ${err.message}`
        );
      }
    }

    // 6. Notify Team
    await this.notificationsService.sendIncidentNotification(savedIncident, savedRca, rollbackEvent);

    return {
      incident: savedIncident,
      rca: savedRca,
      rollback: rollbackEvent,
    };
  }

  async getIncidents(projectId?: string): Promise<IncidentAlertEntity[]> {
    const where = projectId ? { projectId } : {};
    return this.incidentRepo.find({ where, order: { timestamp: 'DESC' } });
  }

  async getRCA(incidentId: string): Promise<RootCauseAnalysisEntity | null> {
    return this.rcaRepo.findOne({ where: { incidentId } });
  }

  async updateStatus(incidentId: string, status: string): Promise<IncidentAlertEntity | null> {
    const incident = await this.incidentRepo.findOne({ where: { id: incidentId } });
    if (!incident) return null;
    
    const oldStatus = incident.status;
    incident.status = status;
    if (status === 'resolved') {
      incident.resolvedAt = new Date();
    }
    const finalSaved = await this.incidentRepo.save(incident);

    // T5.4 Timeline lifecycle status checkpoint
    if (status === 'investigating') {
      await this.addTimelineEvent(
        incidentId,
        'investigating',
        'SRE Investigation Started',
        `Incident marked as investigating. SRE team is analyzing live telemetry.`
      );
    } else if (status === 'resolved') {
      await this.addTimelineEvent(
        incidentId,
        'resolved',
        'Incident Resolved',
        `Telemetry metrics returned to normal thresholds. Incident marked as resolved.`
      );
    }

    // Emit live WebSocket event
    try {
      this.eventsGateway.emitGlobalEvent('incident:resolved', finalSaved);
    } catch (err) {
      this.logger.warn(`Failed to emit incident:resolved: ${err.message}`);
    }

    return finalSaved;
  }

  async getStats() {
    const incidents = await this.incidentRepo.find({ take: 200, order: { timestamp: 'DESC' } });
    const total = incidents.length;
    const active = incidents.filter(i => i.status !== 'resolved').length;
    const resolved = incidents.filter(i => i.status === 'resolved').length;

    // Compute avg MTTR from resolved incidents
    const resolvedIncidents = incidents.filter(i => i.status === 'resolved' && i.resolvedAt);
    let avgMttrMs = 0;
    if (resolvedIncidents.length > 0) {
      const totalMs = resolvedIncidents.reduce((sum, i) => {
        const ms = new Date(i.resolvedAt!).getTime() - new Date(i.timestamp).getTime();
        return sum + ms;
      }, 0);
      avgMttrMs = totalMs / resolvedIncidents.length;
    }
    const avgMttrMinutes = Math.round(avgMttrMs / 60000);
    const avgMttr = avgMttrMinutes > 0 ? `${avgMttrMinutes}m` : 'N/A';

    const rcaCount = await this.rcaRepo.count();
    const autoRollbacks = await this.rollbackRepo.count({ where: { triggeredBy: 'auto' } });

    return { total, active, resolved, avgMttr, rcaGenerated: rcaCount, autoRollbacks };
  }
}
